language: python
sudo: required
dist: xenial

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"

matrix:
  include:
  - name: Code Checks
    python: 3.6
    stage: linters
    env: TOXENV=code-linters
  - name: CloudFormation Templates Checks
    python: 3.6
    stage: linters
    env: TOXENV=cfn-format-check,cfn-lint,cfn-tests
 - name: Validate integration tests configs
   python: 3.6
   stage: linters
   env: TOXENV=validate-test-configs
   script: cd tests/integration-tests && tox

install:
  - pip install tox-travis

script: cd cli && tox
