language: python

python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"

install: 
  - cd cli
  - if [[ $TRAVIS_PYTHON_VERSION == 2.6 ]]; 
    then pip install -r requirements26.txt; 
    else pip install -r requirements.txt;
    fi
  - pip install -e .
  - cd -

sudo: false

script: sh tests/test.sh
